### ISSUE TITLE
Meta Llama 3 Instruct 70B Q4_K_M M1 Max

### ISSUE THREAD

**Issue by tucher** [dmatora/inference-speed#7]
<img width="1005" alt="Screenshot 2024-05-02 at 22 33 34" src="https://github.com/dmatora/LLM-inference-speed-benchmarks/assets/3611738/3f2966a5-672a-46ac-b7ce-fc3e98ef6750">
<img width="680" alt="Screenshot 2024-05-02 at 20 32 16" src="https://github.com/dmatora/LLM-inference-speed-benchmarks/assets/3611738/e5b63152-abe0-40e0-844f-d82a9bd220d5">

**Comment by yupbank** [comment]
what software is the first screenshot?

**Comment by dmatora** [comment]
It's LM Studio
